apiVersion: apps/v1
kind: Deployment
metadata:
  name: sites-worker
  labels:
    app.kubernetes.io/name: sites-worker
    app.kubernetes.io/component: celery
    app.kubernetes.io/part-of: askcos
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: sites-worker
  template:
    metadata:
      labels:
        pod: sites-worker
        app.kubernetes.io/name: sites-worker
        app.kubernetes.io/component: celery
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
        - name: sites-worker
          image: askcos/askcos-site:2020.07
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 1 -Q sites_worker --pool=gevent -n sites_worker@%h"]
          envFrom:
            - configMapRef:
                name: django-env
      imagePullSecrets:
        - name: regcred
