apiVersion: apps/v1
kind: Deployment
metadata:
  name: tffp-worker
  labels:
    app.kubernetes.io/name: tffp-worker
    app.kubernetes.io/component: celery
    app.kubernetes.io/part-of: askcos
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: tffp-worker
  template:
    metadata:
      labels:
        pod: tffp-worker
        app.kubernetes.io/name: tffp-worker
        app.kubernetes.io/component: celery
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
        - name: tffp-worker
          image: askcos/askcos-site:2020.07
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 5 -Q tffp_worker --pool=gevent -n tffp_worker@%h"]
          envFrom:
            - configMapRef:
                name: django-env
      imagePullSecrets:
        - name: regcred
