version: '2.2'
services:
  nginx:
    image: ${PUBLIC_IMAGE_REGISTRY}nginx:1.17.6
    restart: always
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './uwsgi_params:/etc/nginx/uwsgi_params'
      - './askcos.ssl.cert:/etc/ssl/certs/askcos.ssl.cert'
      - './askcos.ssl.key:/etc/ssl/private/askcos.ssl.key'
      - 'staticdata:/static'
    ports:
      - '80:80'
      - '443:443'

  mysql:
    image: ${PUBLIC_IMAGE_REGISTRY}mysql:5.7
    hostname: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - 'mysql_data:/var/lib/mysql'
    expose:
      - '3306'

  mongo:
    image: ${PUBLIC_IMAGE_REGISTRY}mongo:4.2.2
    command: --wiredTigerCacheSizeGB 1.5
    hostname: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - 'mongo_data:/data/db'
      - 'appdata:/data/app'

  app:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:${VERSION_NUMBER}
    hostname: app
    restart: always
    env_file:
      - .env
      - customization
    environment:
      - VERSION_NUMBER  # this overrides value in .env if a different value was specified to deploy.sh
      - UPDATE_DATE
    command: bash -c "uwsgi --socket :8000 --master --processes=4 --wsgi-file /usr/local/ASKCOS/askcos/wsgi.py"
    expose:
      - '8000'
    volumes:
      - 'staticdata:/usr/local/ASKCOS/askcos/askcos_site/static'
      - 'appdata:/usr/local/ASKCOS/makeit/data'

  te_coordinator:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:${VERSION_NUMBER}
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 2 -Q te_coordinator -n te_coordinator@%h"

  sc_coordinator:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:${VERSION_NUMBER}
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 2 -Q sc_coordinator -n sc_coordinator@%h --pool gevent"

  ft_worker:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:${VERSION_NUMBER}
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 2 -Q ft_worker -n ft_worker@%h"

  cr_network_worker:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:${VERSION_NUMBER}
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 2 -Q cr_network_worker -n cr_network_worker@%h --pool=gevent"

  tb_coordinator_mcts:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:${VERSION_NUMBER}
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 4 -Q tb_coordinator_mcts -n tb_coordinator_mcts@%h --pool=gevent --without-heartbeat"

  tb_c_worker:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:${VERSION_NUMBER}
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 48 -Q tb_c_worker -n tb_c_worker@%h --pool=gevent"

  tb_c_worker_preload:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:${VERSION_NUMBER}
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 1 -Q tb_c_worker_preload -n tb_c_worker_preload@%h"

  sites_worker:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:0.4.0
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 1 -Q sites_worker --pool=gevent -n sites_worker@%h"

  impurity_worker:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:${VERSION_NUMBER}
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 1 -Q impurity_worker --pool=gevent -n impurity_worker@%h"

  atom_mapping_worker:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos:${VERSION_NUMBER}
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 3 -Q atom_mapping_worker --pool=gevent -n atom_mapping_worker@%h"

  template-relevance-reaxys:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos/models:template-relevance-reaxys
    restart: always
    expose:
      - 8501

  fast-filter:
    image: ${ASKCOS_IMAGE_REGISTRY}askcos/models:fast-filter
    restart: always
    expose:
      - 8501

  redis:
    image: ${PUBLIC_IMAGE_REGISTRY}redis:5.0.7
    hostname: redis
    env_file:
      - .env
    restart: always
    expose:
      - '${REDIS_PORT}'
    volumes:
      - 'redisdata:/data'
    command: redis-server --port ${REDIS_PORT}

  rabbit:
    image: ${PUBLIC_IMAGE_REGISTRY}rabbitmq:3.8.2
    hostname: rabbit
    env_file:
      - .env
    restart: always
    expose:
      - '${RABBITMQ_NODE_PORT}'

volumes:
  redisdata:
  mysql_data:
  mongo_data:
  staticdata:
  appdata:
