apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: askcos
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: django
  template:
    metadata:
      labels:
        pod: django
        app.kubernetes.io/name: django
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: askcos
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: staticfiles
          emptyDir: {}
      initContainers:
        - name: migrate
          image: askcos/askcos-site:2020.07
          command: ["/bin/bash"]
          args: ["-c", "python /usr/local/askcos-site/manage.py makemigrations main && python /usr/local/askcos-site/manage.py migrate"]
        - name: collectstatic
          image: askcos/askcos-site:2020.07
          command: ["/bin/bash"]
          args: ["-c", "mv /usr/local/askcos-site/static/* /static/"]
          volumeMounts:
            - name: staticfiles
              mountPath: /static
      containers:
        - name: nginx
          image: nginx:1.17.6
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
            - name: staticfiles
              mountPath: /static
        - name: django
          image: askcos/askcos-site:2020.07
          command: ["/bin/bash"]
          args: ["-c", "uwsgi --http :8000 --master --processes=4 --wsgi-file /usr/local/askcos-site/wsgi.py"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-env
            - configMapRef:
                name: django-customization
          resources:
            requests:
              memory: "5Gi"
      imagePullSecrets:
        - name: regcred
