{{- range .Values.celery }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app.kubernetes.io/component: {{ .name }}
    {{- include "askcos.common.matchLabels" $ | nindent 4 }}
    {{- include "askcos.common.metaLabels" $ | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .name }}
      {{- include "askcos.common.matchLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .name }}
        {{- include "askcos.common.matchLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "askcos.serviceAccountName" $ }}
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.app.image.repository }}:{{ $.Values.app.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.app.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "{{ .cmd }}"]
          envFrom:
            - configMapRef:
                name: django-env
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
---
{{ end }}
