apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: askcos
spec:
  type: ClusterIP
  ports:
  - name: django
    port: 8000
    targetPort: 8000
  selector:
    pod: django
