apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "askcos.fullname" . }}
  labels:
    {{- include "askcos.app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "askcos.app.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "askcos.app.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "askcos.serviceAccountName" . }}
      volumes:
        - name: staticfiles
          emptyDir: {}
      initContainers:
        - name: migrate
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "python /usr/local/askcos-site/manage.py makemigrations main && python /usr/local/askcos-site/manage.py migrate"]
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "uwsgi --http :8000 --master --processes=4 --wsgi-file /usr/local/askcos-site/wsgi.py"]
          ports:
            - containerPort: {{ .Values.app.service.port }}
          envFrom:
            - configMapRef:
                name: django-env
            - configMapRef:
                name: django-customization
          resources:
            requests:
              memory: "5Gi"
