apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: askcos
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas.django }}
{{- end }}
  selector:
    matchLabels:
      pod: django
  template:
    metadata:
      labels:
        pod: django
        app.kubernetes.io/name: django
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: askcos
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: staticfiles
          emptyDir: {}
      initContainers:
        - name: migrate
          image: "{{ .Values.images.askcos.repository }}:{{ .Values.images.askcos.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "python /usr/local/askcos-site/manage.py makemigrations main && python /usr/local/askcos-site/manage.py migrate"]
        - name: collectstatic
          image: "{{ .Values.images.askcos.repository }}:{{ .Values.images.askcos.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "cp /usr/local/askcos-site/static/* /static/"]
          volumeMounts:
            - name: staticfiles
              mountPath: /static
      containers:
        - name: django
          image: "{{ .Values.images.askcos.repository }}:{{ .Values.images.askcos.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "uwsgi --http :8000 --master --processes=4 --wsgi-file /usr/local/askcos-site/wsgi.py"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-env
            - configMapRef:
                name: django-customization
          resources:
            requests:
              memory: "5Gi"
