apiVersion: v1
kind: Service
metadata:
  name: {{ include "askcos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "askcos.app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - name: {{ .Values.app.name }}
    port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.port }}
  selector:
    {{- include "askcos.app.matchLabels" . | nindent 4 }}
