apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.nginx.name }}
  labels:
    {{- include "askcos.nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort.http }}
    {{- if .Values.nginx.containerPorts.https }}
    - name: https
      port: {{ .Values.nginx.service.httpsPort }}
      targetPort: {{ .Values.nginx.service.targetPort.https }}
    {{- end }}
  selector:
    {{- include "askcos.nginx.matchLabels" . | nindent 4 }}
