{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "askcos.imagePullSecret" . }}
{{- end }}
