{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "askcos.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "askcos.common.matchLabels" . | nindent 4 }}
    {{- include "askcos.common.metaLabels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
