apiVersion: v1
kind: Service
metadata:
  name: fast-filter
  labels:
    app.kubernetes.io/name: fast-filter
    app.kubernetes.io/component: tfserving
    app.kubernetes.io/part-of: askcos
spec:
  selector:
    pod: fast-filter
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
