apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-relevance-reaxys
  labels:
    app.kubernetes.io/name: template-relevance-reaxys
    app.kubernetes.io/component: tfserving
    app.kubernetes.io/part-of: askcos
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: template-relevance-reaxys
  template:
    metadata:
      labels:
        pod: template-relevance-reaxys
        app.kubernetes.io/name: template-relevance-reaxys
        app.kubernetes.io/component: tfserving
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
        - name: template-relevance-reaxys
          image: askcos/template-relevance-reaxys:1.0
          ports:
            - containerPort: 8501
      imagePullSecrets:
        - name: regcred
