apiVersion: apps/v1
kind: Deployment
metadata:
  name: atom-mapping-worker
  labels:
    app.kubernetes.io/name: atom-mapping-worker
    app.kubernetes.io/component: celery
    app.kubernetes.io/part-of: askcos
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: atom-mapping-worker
  template:
    metadata:
      labels:
        pod: atom-mapping-worker
        app.kubernetes.io/name: atom-mapping-worker
        app.kubernetes.io/component: celery
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
        - name: atom-mapping-worker
          image: registry.gitlab.com/mlpds_mit/askcos/askcos-site:2020.07
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 3 -Q atom_mapping_worker --pool=gevent -n atom_mapping_worker@%h"]
          envFrom:
            - configMapRef:
                name: django-env
      imagePullSecrets:
        - name: regcred
