apiVersion: apps/v1
kind: Deployment
metadata:
  name: cr-network-worker
  labels:
    app.kubernetes.io/name: cr-network-worker
    app.kubernetes.io/component: celery
    app.kubernetes.io/part-of: askcos
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: cr-network-worker
  template:
    metadata:
      labels:
        pod: cr-network-worker
        app.kubernetes.io/name: cr-network-worker
        app.kubernetes.io/component: celery
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
        - name: cr-network-worker
          image: registry.gitlab.com/mlpds_mit/askcos/askcos-site:2020.07
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 2 -Q cr_network_worker -n cr_network_worker@%h"]
          envFrom:
            - configMapRef:
                name: django-env
      imagePullSecrets:
        - name: regcred
