apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-worker
  labels:
    app.kubernetes.io/name: ft-worker
    app.kubernetes.io/component: celery
    app.kubernetes.io/part-of: askcos
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: ft-worker
  template:
    metadata:
      labels:
        pod: ft-worker
        app.kubernetes.io/name: ft-worker
        app.kubernetes.io/component: celery
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
        - name: ft-worker
          image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 2 -Q ft_worker -n ft_worker@%h"]
          envFrom:
            - configMapRef:
                name: django-config
      imagePullSecrets:
        - name: regcred
