apiVersion: apps/v1
kind: Deployment
metadata:
  name: impurity-worker
  labels:
    app.kubernetes.io/name: impurity-worker
    app.kubernetes.io/component: celery
    app.kubernetes.io/part-of: askcos
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: impurity-worker
  template:
    metadata:
      labels:
        pod: impurity-worker
        app.kubernetes.io/name: impurity-worker
        app.kubernetes.io/component: celery
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
        - name: impurity-worker
          image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 1 -Q impurity_worker --pool=gevent -n impurity_worker@%h"]
          envFrom:
            - configMapRef:
                name: django-config
      imagePullSecrets:
        - name: regcred
