apiVersion: apps/v1
kind: Deployment
metadata:
  name: tb-c-worker
  labels:
    app.kubernetes.io/name: tb-c-worker
    app.kubernetes.io/component: celery
    app.kubernetes.io/part-of: askcos
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: tb-c-worker
  template:
    metadata:
      labels:
        pod: tb-c-worker
        app.kubernetes.io/name: tb-c-worker
        app.kubernetes.io/component: celery
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
        - name: tb-c-worker
          image: registry.gitlab.com/mlpds_mit/askcos/askcos:2020.04
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 12 -Q tb_c_worker -n tb_c_worker@%h --pool=gevent"]
          envFrom:
            - configMapRef:
                name: django-config
          resources:
            requests:
              memory: "1.0G"
      imagePullSecrets:
        - name: regcred
