apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-filter
  labels:
    app.kubernetes.io/name: fast-filter
    app.kubernetes.io/component: tfserving
    app.kubernetes.io/part-of: askcos
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: fast-filter
  template:
    metadata:
      labels:
        pod: fast-filter
        app.kubernetes.io/name: fast-filter
        app.kubernetes.io/component: tfserving
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
        - name: fast-filter
          image: registry.gitlab.com/mlpds_mit/askcos/askcos/models:fast-filter
          ports:
            - containerPort: 8501
      imagePullSecrets:
        - name: regcred
