apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  labels:
    app.kubernetes.io/name: rabbit
    app.kubernetes.io/component: message
    app.kubernetes.io/part-of: askcos
spec:
  selector:
    matchLabels:
      pod: rabbit
  replicas: 1
  template:
    metadata:
      labels:
        pod: rabbit
        app.kubernetes.io/name: rabbit
        app.kubernetes.io/component: message
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3.8.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5672
