apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    app.kubernetes.io/name: rabbit
    app.kubernetes.io/component: message
    app.kubernetes.io/part-of: askcos
spec:
  selector:
    pod: rabbit
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
