apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: askcos
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    pod: mongo